-- Legacy schema entrypoint retained for humans and older docs.
-- Source of truth now lives in:
--   1. src/main/resources/db/migration/V1__baseline.sql
--   2. src/main/resources/db/migration/V{n}__*.sql for every later schema change
--
-- Do not append new DDL here.
-- For a pre-Flyway database that already matches the baseline schema, run:
--   mvn -q -f backend/pom.xml \
--     -Dflyway.url=jdbc:mysql://<host>:<port>/<db> \
--     -Dflyway.user=<user> \
--     -Dflyway.password=<password> \
--     flyway:baseline
--
-- After baseline, all schema evolution must go through versioned Flyway migrations.
