-- AINovel V13: durable provenance for generated scene drafts and subsequent edits.

CREATE TABLE `scene_generation_runs` (
  `id` binary(16) NOT NULL,
  `manuscript_id` binary(16) NOT NULL,
  `scene_id` binary(16) NOT NULL,
  `generation_version_id` binary(16) NOT NULL,
  `created_by` binary(16) NOT NULL,
  `previous_run_id` binary(16) DEFAULT NULL,
  `superseded_by_run_id` binary(16) DEFAULT NULL,
  `status` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `attribution_status` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `mode` varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL,
  `model_key` varchar(120) COLLATE utf8mb4_unicode_ci NOT NULL,
  `prompt_version` varchar(120) COLLATE utf8mb4_unicode_ci NOT NULL,
  `attempt_count` int NOT NULL DEFAULT 1,
  `context_hash` char(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `prompt_hash` char(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `context_manifest_json` longtext COLLATE utf8mb4_unicode_ci,
  `generated_content_hash` char(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `current_content_hash` char(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `generated_characters` int NOT NULL,
  `current_characters` int DEFAULT NULL,
  `retained_characters` int DEFAULT NULL,
  `added_characters` int DEFAULT NULL,
  `deleted_characters` int DEFAULT NULL,
  `retention_rate` decimal(8,6) DEFAULT NULL,
  `exact_match` bit(1) DEFAULT NULL,
  `diff_json` longtext COLLATE utf8mb4_unicode_ci,
  `tags_json` longtext COLLATE utf8mb4_unicode_ci,
  `note` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `preference_confirmed` bit(1) NOT NULL DEFAULT 0,
  `preference_confirmed_at` datetime(6) DEFAULT NULL,
  `first_edited_at` datetime(6) DEFAULT NULL,
  `last_edited_at` datetime(6) DEFAULT NULL,
  `recomputed_at` datetime(6) DEFAULT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_scene_generation_run_scene` (`manuscript_id`,`scene_id`,`created_at`),
  KEY `idx_scene_generation_run_active` (`manuscript_id`,`scene_id`,`status`),
  KEY `idx_scene_generation_run_version` (`generation_version_id`),
  KEY `idx_scene_generation_run_created_by` (`created_by`),
  KEY `idx_scene_generation_run_previous` (`previous_run_id`),
  KEY `idx_scene_generation_run_superseded_by` (`superseded_by_run_id`),
  CONSTRAINT `fk_scene_generation_run_manuscript` FOREIGN KEY (`manuscript_id`) REFERENCES `manuscripts` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_scene_generation_run_version` FOREIGN KEY (`generation_version_id`) REFERENCES `manuscript_versions` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_scene_generation_run_created_by` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_scene_generation_run_previous` FOREIGN KEY (`previous_run_id`) REFERENCES `scene_generation_runs` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_scene_generation_run_superseded_by` FOREIGN KEY (`superseded_by_run_id`) REFERENCES `scene_generation_runs` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
