-- AINovel V5: durable G1 guided-creation workflows and background jobs.

CREATE TABLE `creation_workflow_runs` (
  `id` binary(16) NOT NULL,
  `user_id` binary(16) NOT NULL,
  `story_id` binary(16) DEFAULT NULL,
  `world_id` binary(16) DEFAULT NULL,
  `outline_id` binary(16) DEFAULT NULL,
  `active_job_id` binary(16) DEFAULT NULL,
  `template_key` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `current_step` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `status` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `seed_idea` varchar(1000) COLLATE utf8mb4_unicode_ci NOT NULL,
  `genre` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tone` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `target_chapter_count` int NOT NULL DEFAULT 6,
  `auto_run` bit(1) NOT NULL DEFAULT b'0',
  `steps_json` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `error_message` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `completed_at` datetime(6) DEFAULT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  `version` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_creation_workflow_user_updated` (`user_id`,`updated_at`),
  KEY `idx_creation_workflow_status` (`status`,`updated_at`),
  CONSTRAINT `fk_creation_workflow_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_creation_workflow_story` FOREIGN KEY (`story_id`) REFERENCES `stories` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_creation_workflow_world` FOREIGN KEY (`world_id`) REFERENCES `worlds` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_creation_workflow_outline` FOREIGN KEY (`outline_id`) REFERENCES `outlines` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `async_jobs` (
  `id` binary(16) NOT NULL,
  `user_id` binary(16) NOT NULL,
  `scope_id` binary(16) NOT NULL,
  `job_type` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `step` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `status` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `progress` int NOT NULL DEFAULT 0,
  `attempt_count` int NOT NULL DEFAULT 0,
  `idempotency_key` varchar(160) COLLATE utf8mb4_unicode_ci NOT NULL,
  `payload_json` longtext COLLATE utf8mb4_unicode_ci,
  `result_json` longtext COLLATE utf8mb4_unicode_ci,
  `error_message` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `charged_credits` bigint NOT NULL DEFAULT 0,
  `remaining_credits` bigint NOT NULL DEFAULT 0,
  `lease_owner` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `lease_until` datetime(6) DEFAULT NULL,
  `completed_at` datetime(6) DEFAULT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_async_job_idempotency` (`idempotency_key`),
  KEY `idx_async_job_scope_created` (`scope_id`,`created_at`),
  KEY `idx_async_job_status_lease` (`status`,`lease_until`),
  CONSTRAINT `fk_async_job_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
